### ISSUE TITLE
Invalid XML in source files

### ISSUE THREAD

**Issue by fsanzl** [ofmgraz/transkribus-out#10]
`1499840.xml: ID facs_2_tr_1696527148 already defined, line 52, column 128 (1499840.xml, line 52)`
(Defined several times)

**Comment by fsanzl** [comment]
it comes messed up from Transkribus or appears after the transformation with page2tei-0.xsl

**Comment by fsanzl** [comment]
1499840_mets.xml validates

**Comment by fsanzl** [comment]
Now, it produces an error.
`tei/1499840.xml: ID facs_2_tr_1696527148 already defined, line 52, column 128 (1499840.xml, line 52)
Traceback (most recent call last):
  File "/home/fernando/Projects/ofmgraz/transkribus-out/./make_tei.py", line 21, in <module>
    tei_source = maketei.TeiTree(source_table, input_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fernando/Projects/ofmgraz/transkribus-out/maketei.py", line 54, in __init__
    self.tkb = self.amend_pics_url(self.tkb, self.doc_id)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fernando/Projects/ofmgraz/transkribus-out/maketei.py", line 74, in amend_pics_url
    graphic_elements = tree.any_xpath(".//tei:graphic")
                       ^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'any_xpath'`

I will try a different approach by renaming using regex instead of parsing the XML.
